
// Output Statements 

// document.writeln('Hello');
// console.log('Hello Guys');
// window.alert('hi');
// window.Confirm('Are you Ready To Learn JS ?');

// Variables 

// 1.var 

// var firsname1 = 'Imran';
// var firsname2= 'raja';
// console.log(firsname1,firsname2);

// 2.let

// let age = 25;
// console.log(age);

// 3.const 
// const pi = 3.14;
// console.log(pi);
// const isstudent = false;
// console.log(isstudent);

